name: Publish to Maven Central

run-name: Publish to Maven Central (${{ github.event.release.tag_name || github.event.client_payload.tag_name || inputs.tag_name }})

on:
  repository_dispatch:
    types:
      - publish-maven-central

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.release.tag_name || github.event.client_payload.tag_name || inputs.tag_name }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish release to Maven Central
    if: ${{ (github.event_name == 'release' && !github.event.release.prerelease) || (github.event_name == 'repository_dispatch' && !github.event.client_payload.prerelease) || (github.event_name == 'workflow_dispatch' && !inputs.prerelease) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.client_payload.tag_name || inputs.tag_name }}

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Free gradlew
        run: chmod +x ./gradlew

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew :langjal:publishToMavenCentral
